<a href="https://colab.research.google.com/github/vanessamr/intro_dc/blob/main/Introducci%C3%B3nDC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tipos de Datos:
**Numericos:**
*   Continuo: velocidad de un avión
*   Discreto: No. de personas

**Categoricos:**
* Nominal: Casado/soltero
* Ordinal: Edad


Tambien se puede dividir en informacion estructurada y no estructurada:
* Estructurada: Una tabla, como SQL
* No estructurada: videos, texto, imagenes, como: No SQL, archivo JSON, TXT, PDF, etc.



#Tipos de estadistica



*   Descriptiva: Describe los datos que tenemos
*   Imferemcial: Utiliza esos datos para inferir algo sobre la población 



**Proceso:**


*   Filtrar: Plantear un caso particular
*   Agrupar: Piensa en una o varias categorias que permitan el agrupar los datos
*   Colapsar: Factor medible que afecte a todas los grupos. 



In [ ]:
import csv

In [ ]:
#archivo subido directamente de coolab (recuerda seleccionar el archivo y con clic derecho poner donde dice copiar ruta de acceso y es lo que se pega en los parentesis)
filecsv =open ('/data-text.csv', 'r')

In [ ]:
#para drive
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
#Abrir documento de drive, solo que esta es xlsx
drivefile= open('/content/drive/MyDrive/gen.xlsx', 'r')

In [ ]:
#Para leer un archivo forma 1 para csv
for row in filecsv:
  print(row)

Se truncaron las últimas líneas 5000 del resultado de transmisión.

"Life expectancy at age 60 (years)","Published","2012","Americas","Upper-middle-income","Jamaica","Both sexes","21","21.00000","","",""

"Life expectancy at birth (years)","Published","2012","Europe","Upper-middle-income","Kazakhstan","Female","72","72.00000","","",""

"Life expectancy at birth (years)","Published","1990","Europe","Upper-middle-income","Kazakhstan","Both sexes","66","66.00000","","",""

"Life expectancy at birth (years)","Published","1990","Americas","Upper-middle-income","Saint Kitts and Nevis","Female","71","71.00000","","",""

"Life expectancy at age 60 (years)","Published","1990","Americas","Upper-middle-income","Saint Kitts and Nevis","Female","19","19.00000","","",""

"Life expectancy at birth (years)","Published","1990","Eastern Mediterranean","Upper-middle-income","Lebanon","Male","64","64.00000","","",""

"Life expectancy at birth (years)","Published","1990","Eastern Mediterranean","Upper-midd

In [ ]:
#leer un archivo forma 2:
with open('/data-text.csv', 'r') as file:
  print(file.read())

"Indicator","PUBLISH STATES","Year","WHO region","World Bank income group","Country","Sex","Display Value","Numeric","Low","High","Comments"
"Life expectancy at birth (years)","Published","1990","Europe","High-income","Andorra","Both sexes","77","77.00000","","",""
"Life expectancy at birth (years)","Published","2000","Europe","High-income","Andorra","Both sexes","80","80.00000","","",""
"Life expectancy at age 60 (years)","Published","2012","Europe","High-income","Andorra","Female","28","28.00000","","",""
"Life expectancy at age 60 (years)","Published","2000","Europe","High-income","Andorra","Both sexes","23","23.00000","","",""
"Life expectancy at birth (years)","Published","2012","Eastern Mediterranean","High-income","United Arab Emirates","Female","78","78.00000","","",""
"Life expectancy at birth (years)","Published","2000","Americas","High-income","Antigua and Barbuda","Male","72","72.00000","","",""
"Life expectancy at age 60 (years)","Published","1990","Americas","High-income"

In [ ]:
#instalar pandas
!pip install pandas

In [ ]:
import pandas as pd


In [ ]:
# leer un archivo csv forma 3:
pd.read_csv('/data-text.csv')

Indicator PUBLISH STATES  Year  \
0                    Life expectancy at birth (years)      Published  1990   
1                    Life expectancy at birth (years)      Published  2000   
2                   Life expectancy at age 60 (years)      Published  2012   
3                   Life expectancy at age 60 (years)      Published  2000   
4                    Life expectancy at birth (years)      Published  2012   
...                                               ...            ...   ...   
4651  Healthy life expectancy (HALE) at birth (years)      Published  2012   
4652  Healthy life expectancy (HALE) at birth (years)      Published  2012   
4653  Healthy life expectancy (HALE) at birth (years)      Published  2000   
4654  Healthy life expectancy (HALE) at birth (years)      Published  2000   
4655  Healthy life expectancy (HALE) at birth (years)      Published  2012   

                 WHO region World Bank income group               Country  \
0                    Europe             High-income               Andorra   
1                    Europe             High-income               Andorra   
2                    Europe             High-income               Andorra   
3                    Europe             High-income               Andorra   
4     Eastern Mediterranean             High-income  United Arab Emirates   
...                     ...                     ...                   ...   
4651        Western Pacific     Lower-middle-income                 Samoa   
4652  Eastern Mediterranean              Low-income                 Yemen   
4653                 Africa     Upper-middle-income          South Africa   
4654                 Africa              Low-income                Zambia   
4655                 Africa              Low-income              Zimbabwe   

             Sex  Display Value  Numeric  Low  High  Comments  
0     Both sexes             77     77.0  NaN   NaN       NaN  
1     Both sexes             80     80.0  NaN   NaN       NaN  
2         Female             28     28.0  NaN   NaN       NaN  
3     Both sexes             23     23.0  NaN   NaN       NaN  
4         Female             78     78.0  NaN   NaN       NaN  
...          ...            ...      ...  ...   ...       ...  
4651      Female             66     66.0  NaN   NaN       NaN  
4652  Both sexes             54     54.0  NaN   NaN       NaN  
4653        Male             49     49.0  NaN   NaN       NaN  
4654  Both sexes             36     36.0  NaN   NaN       NaN  
4655      Female             51     51.0  NaN   NaN       NaN  

[4656 rows x 12 columns]

In [ ]:
#importar excel:
excel=pd.ExcelFile('/tags.xlsx')

In [ ]:
#para poer abrir el archivo, se debe poner la pagina que se debe leer.
excel.sheet_names

['tags', 'hoja2']

In [ ]:
excel.parse('tags')

userId   movieId               tag     timestamp
0        2.0   60756.0             funny  1.445715e+09
1        2.0   60756.0   Highly quotable  1.445715e+09
2        2.0   60756.0      will ferrell  1.445715e+09
3        2.0   89774.0      Boxing story  1.445715e+09
4        2.0   89774.0               MMA  1.445715e+09
...      ...       ...               ...           ...
3678   606.0    7382.0         for katie  1.171234e+09
3679   606.0    7936.0           austere  1.173392e+09
3680   610.0    3265.0            gun fu  1.493844e+09
3681   610.0    3265.0  heroic bloodshed  1.493844e+09
3682   610.0  168248.0  Heroic Bloodshed  1.493844e+09

[3683 rows x 4 columns]

In [ ]:
excel.parse('hoja2')

Empty DataFrame
Columns: []
Index: []

In [ ]:
#importar con JSON
#Primero se importa un paquete llamao json
import json
json_data = open('/data-text.json').read()

In [ ]:
json_data

'[\n  {\n    "Indicator":"Life expectancy at birth (years)",\n    "PUBLISH STATES":"Published",\n    "Year":1990,\n    "WHO region":"Europe",\n    "World Bank income group":"High-income",\n    "Country":"Andorra",\n    "Sex":"Both sexes",\n    "Display Value":77,\n    "Numeric":77.00000,\n    "Low":"",\n    "High":"",\n    "Comments":""\n  },\n  {\n    "Indicator":"Life expectancy at birth (years)",\n    "PUBLISH STATES":"Published",\n    "Year":2000,\n    "WHO region":"Europe",\n    "World Bank income group":"High-income",\n    "Country":"Andorra",\n    "Sex":"Both sexes",\n    "Display Value":80,\n    "Numeric":80.00000,\n    "Low":"",\n    "High":"",\n    "Comments":""\n  },\n  {\n    "Indicator":"Life expectancy at age 60 (years)",\n    "PUBLISH STATES":"Published",\n    "Year":2012,\n    "WHO region":"Europe",\n    "World Bank income group":"High-income",\n    "Country":"Andorra",\n    "Sex":"Female",\n    "Display Value":28,\n    "Numeric":28.00000,\n    "Low":"",\n    "High":"",

In [ ]:
data = json.loads(json_data)

In [ ]:
data

[{'Comments': '',
  'Country': 'Andorra',
  'Display Value': 77,
  'High': '',
  'Indicator': 'Life expectancy at birth (years)',
  'Low': '',
  'Numeric': 77.0,
  'PUBLISH STATES': 'Published',
  'Sex': 'Both sexes',
  'WHO region': 'Europe',
  'World Bank income group': 'High-income',
  'Year': 1990},
 {'Comments': '',
  'Country': 'Andorra',
  'Display Value': 80,
  'High': '',
  'Indicator': 'Life expectancy at birth (years)',
  'Low': '',
  'Numeric': 80.0,
  'PUBLISH STATES': 'Published',
  'Sex': 'Both sexes',
  'WHO region': 'Europe',
  'World Bank income group': 'High-income',
  'Year': 2000},
 {'Comments': '',
  'Country': 'Andorra',
  'Display Value': 28,
  'High': '',
  'Indicator': 'Life expectancy at age 60 (years)',
  'Low': '',
  'Numeric': 28.0,
  'PUBLISH STATES': 'Published',
  'Sex': 'Female',
  'WHO region': 'Europe',
  'World Bank income group': 'High-income',
  'Year': 2012},
 {'Comments': '',
  'Country': 'Andorra',
  'Display Value': 23,
  'High': '',
  'Indica

In [ ]:
#para convertir en data frame
pd.DataFrame(data)

Indicator PUBLISH STATES  Year  \
0                    Life expectancy at birth (years)      Published  1990   
1                    Life expectancy at birth (years)      Published  2000   
2                   Life expectancy at age 60 (years)      Published  2012   
3                   Life expectancy at age 60 (years)      Published  2000   
4                    Life expectancy at birth (years)      Published  2012   
...                                               ...            ...   ...   
4651  Healthy life expectancy (HALE) at birth (years)      Published  2012   
4652  Healthy life expectancy (HALE) at birth (years)      Published  2012   
4653  Healthy life expectancy (HALE) at birth (years)      Published  2000   
4654  Healthy life expectancy (HALE) at birth (years)      Published  2000   
4655  Healthy life expectancy (HALE) at birth (years)      Published  2012   

                 WHO region World Bank income group               Country  \
0                    Europe             High-income               Andorra   
1                    Europe             High-income               Andorra   
2                    Europe             High-income               Andorra   
3                    Europe             High-income               Andorra   
4     Eastern Mediterranean             High-income  United Arab Emirates   
...                     ...                     ...                   ...   
4651        Western Pacific     Lower-middle-income                 Samoa   
4652  Eastern Mediterranean              Low-income                 Yemen   
4653                 Africa     Upper-middle-income          South Africa   
4654                 Africa              Low-income                Zambia   
4655                 Africa              Low-income              Zimbabwe   

             Sex  Display Value  Numeric Low High Comments  
0     Both sexes             77     77.0                    
1     Both sexes             80     80.0                    
2         Female             28     28.0                    
3     Both sexes             23     23.0                    
4         Female             78     78.0                    
...          ...            ...      ...  ..  ...      ...  
4651      Female             66     66.0                    
4652  Both sexes             54     54.0                    
4653        Male             49     49.0                    
4654  Both sexes             36     36.0                    
4655      Female             51     51.0                    

[4656 rows x 12 columns]

In [ ]:
#obtener datos API
import requests

In [ ]:
response = requests.get()

# **Introduccion a NumPy**
Recordatorio de listas en phyton:
-append:Agrega elementos al final de la lista 
- List[0:]: ded imprimen todos los elemento de la lista del cero en adelante 
- List[:]: inmprime todos los elementos
- remove o pop: quitar elemento

NumPy ayuda a hacer que todo sea mas rapido
Se les suelen atribuir dos características importantes:
- Todos los datos dentro de un numpy array deben ser de un mismo tipo. Si se intenta ingresar un dato de otro tipo, se forzará a ese dato a convertirse en el tipo de dato predominante.
- Pueden ser estructuras de una dimensión, de dos dimensiones, incluso de 7 dimensiones. Sin embargo, al menos en análisis de datos, siempre es mejor tratar con información en en forma matricial (dos dimensiones).
Se refiere a dimenciones a los elementos que lo componen. Por ejemplo:
  a) Elemento de cero dimensiones: Escalar, un numero o palabra (punto). Ej: 1, true, F
  b) Elemento de una dimensión: vector, Una lista (recta). Ej. [1,2,4,true]
  c) Elemento de dos dimensioes: Una matríz [[1,3,4,], [2,3,4], [5,4,3]]
  d) Elemento de tres dimensiones: Tensores. Ej. una imagen

Lps numpys transforman estos elementos en elementos n dimensionales.

Funciona para hacer operaciones entre listas, por ejemplo cuando se necesita sacar el imc, con solo tener el peso y masa

In [ ]:
#Para inportar numpy se utiliza:
import numpy as np
#Solo puede contener datos de un solo tipo, por ejemplo:
np.array ([1.0, 'is', True])
#Numpy lo que hace es elegir una estructura de datos para todos, por eso pone '' en los numeros también.


array(['1.0', 'is', 'True'], dtype='<U32')

In [ ]:
#Tambien puede concatenar dos tipos de listas, por ejemplo:
python_list = [1, 2, 3] # Lista

python_list + python_list

[1, 2, 3, 1, 2, 3]

In [ ]:
#se pueden hacer operaciones cuando son array
numpy_array = np.array([1, 2, 3]) # Arreglo Numpy
# Sumando arreglos
numpy_array + numpy_array

array([2, 4, 6])

In [ ]:
# Muktiplicado arreglos
numpy_array*numpy_array

array([1, 4, 9])

Problema: Calcular el BMI de un grupo de personas

In [ ]:
# Generamos una nueva lista con las estaturas de las personas en el grupo
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height


[1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
# Generamos una nueva lista con los pesos de las personas en el grupo
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
# Sin embargo, no es posible realizar operaciones sobre los
# elementos de la lista de esta manera
weight / height ** 2

TypeError: ignored

In [ ]:
# Importar el paquete numpy como np
import numpy as np

# Crear 2 array numpy desde height y weight
np_height = np.array(height)
np_weight = np.array(weight)

In [ ]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
#igual se pueden revisar cuales son los numeros que se encuentran el array, por ejemplo:
bmi [0]

21.85171572722109

In [ ]:
#o analizar valores de manera mas facil y lo respondera de manera buleana:
bmi <23

array([ True,  True,  True, False,  True])

In [ ]:
#igual se pueden hacer operaciones
bmi*2

array([43.70343145, 41.95011338, 43.50056428, 49.494695  , 42.88255672])

In [ ]:
#se pueden buscar algunos elementos con conocimiento previo
bmi[bmi<23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

In [ ]:
# Este es de una sola dimensión (arreglo)
type(np_height)

numpy.ndarray

In [ ]:
#Para cada dimunsión interna se representa por [][],[]
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7]])

np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

muestreo en 2 dimensiones

In [ ]:
# Una fila completa
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
# El elemento en la primera fila, segunda columna
np_2d[0][2]

1.71

In [ ]:
# El elemento en la primera fila, segunda columna con notación de coma
np_2d[0,2]

1.71

In [ ]:
# Los elementos de todas las filas pero en las columnas 1, 2
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [ ]:
# Los elementos de la segunda fila pero todas las columnas 
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

Estadística básica con Numpy
FIFA nos ha proveído amablemente de una base de datos con todo tipo de métricas acerca de jugadores en todos los equipos del mundo. Nosotros, la hemos pedido pues tenemos una corazonada: Creemos que los jugadores que juegan en la posición de portero, tienen en general una estatura mayor que el resto de jugadores, pero nadie nos cree :(



In [ ]:
# Importamos nuestros datos
import pandas as pd
data = pd.read_csv("https://assets.datacamp.com/production/repositories/288/datasets/026a5211b906ac118a09b1a0dbf7df48faafb379/fifa.csv") 
# Mostramos las columnas con las que contamos 
data.columns

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')

In [ ]:
data.head(3)

id              name   rating  position   height    foot   rare  pace  \
0    1001      Gábor Király       69        GK      191   Right      0         
1  100143      Frederik Boi       65         M      184   Right      0    61   
2  100264   Tomasz Szewczuk       57         A      185   Right      0    65   

   shooting  passing  dribbling  defending  heading  diving  handling  \
0                                                        70        66   
1        65       63         59         62       62                     
2        54       43         53         55       74                     

   kicking  reflexes  speed   positioning  
0       63        74     35          66.0  
1                                     NaN  
2                                     NaN

In [ ]:
# Convertimos las columnas a Numpy Arrays
np_positions = np.array(data[' position'])
np_heights = np.array(data[' height'])
np_positions

array([' GK', ' M', ' A', ..., ' D', ' D', ' M'], dtype=object)

In [27]:
#cc Heights de los goalkeepers (porteros): gk_heights
gk_heights = np_heights[np_positions == ' GK']

# Heights de los demás jugadores: other_heights
other_heights = np_heights[np_positions != ' GK']

In [ ]:
# Vamos a imprimir la mediana en la estatura de los porteros. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))